force-app/main/default/objects/Mock_Callout_Mapping__mdt/Mock_Callout_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Mock Callout Mapping</label>
    <pluralLabel>Mock Callout Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Mock_Callout_Mapping__mdt/fields/Error_HTTP_Code__c.field-meta.xml
<CustomField>
    <fullName>Error_HTTP_Code__c</fullName>
    <label>Error HTTP Code</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mock_Callout_Mapping__mdt/fields/Error_Method__c.field-meta.xml
<CustomField>
    <fullName>Error_Method__c</fullName>
    <defaultValue>&quot;POST&quot;</defaultValue>
    <label>Error Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>HEAD</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>OPTIONS</fullName>
            </value>
            <value>
                <fullName>CONNECT</fullName>
            </value>
            <value>
                <fullName>TRACE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mock_Callout_Mapping__mdt/fields/Error_Static_Resource_Name__c.field-meta.xml
<CustomField>
    <fullName>Error_Static_Resource_Name__c</fullName>
    <label>Error Static Resource Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mock_Callout_Mapping__mdt/fields/Include_Params__c.field-meta.xml
<CustomField>
    <fullName>Include_Params__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Include string after &apos;?&apos; to match endpoint?</description>
    <label>Include Params?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Mock_Callout_Mapping__mdt/fields/Success_HTTP_Code__c.field-meta.xml
<CustomField>
    <fullName>Success_HTTP_Code__c</fullName>
    <defaultValue>200</defaultValue>
    <label>Success HTTP Code</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mock_Callout_Mapping__mdt/fields/Success_Method__c.field-meta.xml
<CustomField>
    <fullName>Success_Method__c</fullName>
    <defaultValue>&quot;POST&quot;</defaultValue>
    <label>Success Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>HEAD</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>OPTIONS</fullName>
            </value>
            <value>
                <fullName>CONNECT</fullName>
            </value>
            <value>
                <fullName>TRACE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mock_Callout_Mapping__mdt/fields/Success_Static_Resource_Name__c.field-meta.xml
<CustomField>
    <fullName>Success_Static_Resource_Name__c</fullName>
    <description>Static Resource name to pull the JSON from</description>
    <label>Success Static Resource Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CalloutSampleTest.cls
/**
 * @description       : 
 * @author            : Mark Alvin Tayag (tmalvin.workshop@gmail.com)
 * @group             : 
 * @last modified on  : 07-16-2022
 * @last modified by  : Mark Alvin Tayag (tmalvin.workshop@gmail.com)
**/
@isTest
public class CalloutSampleTest {
    @IsTest
    static void testSuccessCallout() {
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(true));
        
        List<Mock_Callout_Mapping__mdt> mdList = [SELECT Endpoint__c, Include_Params__c, 
                                                    Success_HTTP_Code__c, Success_Method__c, Success_Static_Resource_Name__c,
                                                    Error_HTTP_Code__c, Error_Method__c, Error_Static_Resource_Name__c
                                                    FROM Mock_Callout_Mapping__mdt
                                                    WHERE DeveloperName='AWS'];
        List<StaticResource> srList = [SELECT Name, Body FROM StaticResource WHERE Name =: mdList[0].Success_Static_Resource_Name__c];

        Test.startTest();
        String jsonStr = CalloutSample.getCalloutResponseContents(mdList[0].Endpoint__c, mdList[0].Success_Method__c);
        Test.stopTest();
        System.assertEquals(srList[0].Body.toString(), jsonStr);
    }
    
    @IsTest
    static void testErrorCallout() {
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(false));
        
        List<Mock_Callout_Mapping__mdt> mdList = [SELECT Endpoint__c, Include_Params__c, 
                                                    Success_HTTP_Code__c, Success_Method__c, Success_Static_Resource_Name__c,
                                                    Error_HTTP_Code__c, Error_Method__c, Error_Static_Resource_Name__c
                                                    FROM Mock_Callout_Mapping__mdt
                                                    WHERE DeveloperName='AWS'];
        List<StaticResource> srList = [SELECT Name, Body FROM StaticResource WHERE Name =: mdList[0].Error_Static_Resource_Name__c];

        Test.startTest();
        String jsonStr = CalloutSample.getCalloutResponseContents(mdList[0].Endpoint__c, mdList[0].Error_Method__c);
        Test.stopTest();
        System.assertEquals(srList[0].Body.toString(), jsonStr);
    }
}