force-app/main/default/objects/Mock_Callout_Mapping__mdt/Mock_Callout_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Mock Callout Mapping</label>
    <pluralLabel>Mock Callout Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Mock_Callout_Mapping__mdt/fields/Error_HTTP_Code__c.field-meta.xml
<CustomField>
    <fullName>Error_HTTP_Code__c</fullName>
    <label>Error HTTP Code</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mock_Callout_Mapping__mdt/fields/Error_Method__c.field-meta.xml
<CustomField>
    <fullName>Error_Method__c</fullName>
    <defaultValue>&quot;POST&quot;</defaultValue>
    <label>Error Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>HEAD</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>OPTIONS</fullName>
            </value>
            <value>
                <fullName>CONNECT</fullName>
            </value>
            <value>
                <fullName>TRACE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mock_Callout_Mapping__mdt/fields/Error_Static_Resource_Name__c.field-meta.xml
<CustomField>
    <fullName>Error_Static_Resource_Name__c</fullName>
    <label>Error Static Resource Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mock_Callout_Mapping__mdt/fields/Include_Params__c.field-meta.xml
<CustomField>
    <fullName>Include_Params__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Include string after &apos;?&apos; to match endpoint?</description>
    <label>Include Params?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Mock_Callout_Mapping__mdt/fields/Success_HTTP_Code__c.field-meta.xml
<CustomField>
    <fullName>Success_HTTP_Code__c</fullName>
    <defaultValue>200</defaultValue>
    <label>Success HTTP Code</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mock_Callout_Mapping__mdt/fields/Success_Method__c.field-meta.xml
<CustomField>
    <fullName>Success_Method__c</fullName>
    <defaultValue>&quot;POST&quot;</defaultValue>
    <label>Success Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>HEAD</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>OPTIONS</fullName>
            </value>
            <value>
                <fullName>CONNECT</fullName>
            </value>
            <value>
                <fullName>TRACE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mock_Callout_Mapping__mdt/fields/Success_Static_Resource_Name__c.field-meta.xml
<CustomField>
    <fullName>Success_Static_Resource_Name__c</fullName>
    <description>Static Resource name to pull the JSON from</description>
    <label>Success Static Resource Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MockHttpResponseGenerator.cls
/**
 * @description       : 
 * @author            : Mark Alvin Tayag (tmalvin.workshop@gmail.com)
 * @group             : 
 * @last modified on  : 07-16-2022
 * @last modified by  : Mark Alvin Tayag (tmalvin.workshop@gmail.com)
**/
@isTest
public class MockHttpResponseGenerator implements HttpCalloutMock {

    public List<Mock_Callout_Mapping__mdt> mockCalloutList = new List<Mock_Callout_Mapping__mdt>();
    public Map<String, String> srMockMap = new Map<String, String>(); //Name + JSON map
    public String CONTENT_TYPE = 'application/json';
    public Boolean sendSuccess = true;

    public MockHttpResponseGenerator(Boolean isSuccess) {
        sendSuccess = isSuccess;
        Set<String> srNames = new Set<String>();
        for (Mock_Callout_Mapping__mdt md : [SELECT Endpoint__c, Include_Params__c, 
                                Success_HTTP_Code__c, Success_Method__c, Success_Static_Resource_Name__c,
                                Error_HTTP_Code__c, Error_Method__c, Error_Static_Resource_Name__c
                                FROM Mock_Callout_Mapping__mdt]) {
            if (String.isNotEmpty(md.Success_Static_Resource_Name__c)) { srNames.add(md.Success_Static_Resource_Name__c); }
            if (String.isNotEmpty(md.Error_Static_Resource_Name__c)) { srNames.add(md.Error_Static_Resource_Name__c); }
            mockCalloutList.add(md);
        }
        
        for (StaticResource sr : [SELECT Name, Body FROM StaticResource WHERE ContentType =: CONTENT_TYPE AND Name =: srNames]) {
            srMockMap.put(sr.Name, sr.Body.toString());
        }
    }
    
    // Implement this interface method
    public HTTPResponse respond(HTTPRequest req) {
        HttpResponse res = new HttpResponse();
        Mock_Callout_Mapping__mdt md = findMD(req);

        if (String.isEmpty(md.Endpoint__c)) {
            System.assert(false, 'Endpoint mismatch');
        }

        //SUCCESS
        if (sendSuccess == true && (String.isEmpty(md.Success_Static_Resource_Name__c) || !srMockMap.containsKey(md.Success_Static_Resource_Name__c))) {
            System.assert(false, 'JSON Response is not available');
        }
        
        if (md.Success_Method__c == req.getMethod() && sendSuccess == true) {
            res.setHeader('Content-Type', CONTENT_TYPE);
            res.setBody(srMockMap.get(md.Success_Static_Resource_Name__c));
            res.setStatusCode(Integer.valueOf(md.Success_HTTP_Code__c));
        }

        //ERROR
        if (sendSuccess == false && (String.isEmpty(md.Error_Static_Resource_Name__c) || !srMockMap.containsKey(md.Error_Static_Resource_Name__c))) {
            System.assert(false, 'JSON Response is not available');
        }

        if (md.Error_Method__c == req.getMethod() && sendSuccess == false) {
            res.setHeader('Content-Type', CONTENT_TYPE);
            res.setBody(srMockMap.get(md.Error_Static_Resource_Name__c));
            res.setStatusCode(Integer.valueOf(md.Error_HTTP_Code__c));
        }

        return res;
    }

    private Mock_Callout_Mapping__mdt findMD (HttpRequest req) {
        Mock_Callout_Mapping__mdt md = new Mock_Callout_Mapping__mdt();

        for (Mock_Callout_Mapping__mdt meta : mockCalloutList) {
            if ((meta.Endpoint__c == req.getEndpoint() && meta.Include_Params__c == true) || 
                (meta.Endpoint__c.startsWith(req.getEndpoint()) && meta.Include_Params__c == false)) {
                    md = meta;
                    break;
                }
        }

        return md;
    }
}